### ISSUE TITLE
Multiplying by a percent that goes down to 3 decimal places

### ISSUE THREAD

**Issue by zachfeldman** [ikr/money-math#22]
This may be a stupid question and I read through https://github.com/ikr/money-math/issues/8, but what if I have a percentage that goes down to 3 decimal places? For instance, the NY state tax rate is 8.875%. It doesn't seem like this library can handle that type of percentage, unless I am missing something? It always seems to round it to 8.8%. Thanks for any help and the great lib @ikr !

**Comment by ikr** [comment]
Actually, that's a great question. It's a fair case to handle, I guess. I just never stumbled on a sub-hundredth percentages before. Indeed, treating percentages as _amounts_ is ungrounded and pretty much arbitrary. I'd accept a pull request supporting the 8.875%.

**Comment by zachfeldman** [comment]
Cool, I took a look at `money.js` and see that all percentage arguments are parsed as `amounts` 

```js
new BigInteger(Money.amountToCents(percent))
```

Then they're multiplied, which also calls `Money.amountToCents(percent);`.

Can you think of any other functions that would be affected by this PR - maybe `div`?

I want to make sure I don't violate any of the assumptions of your mathematical model. Can you explain just a little more how I could avoid doing that while still modifying the methods to do this calculation? I can do the actual grunt work of writing and validating....

Glad to submit a PR when I'm done!

**Comment by ikr** [comment]
Right. In the `percent`'s case, we'd have to bring fractions to a common denominator, to make all the numbers whole. Say, 8.875% of 1'000 -- 8'875 and 1'000'000 -- denominated by a 1'000. Then:

| 100 * 1'000 | 1'000'000 |
| --- | --- |
| 8875 | X |

X = 8875 * 10^6 / 10^5 = 88'750

And then, back to the original units, dividing by the common denominator -- 88'750 / 1'000 = 88.75. That's where we're going to do the rounding, if the division results in a sub-cent value.  

Regarding the `div`, may be the API should be changed to only support integer divisors. I'll consider removing the `div` from the public API, and introducing a `split(amount, parts)` instead.

**Comment by zachfeldman** [comment]
Sorry @ikr , ended up going with https://github.com/davidkalosi/js-money because they had all the tools I needed. Just thought I'd report back and close my issue rather than leave a hanging thread!

**Comment by ikr** [comment]
@zachfeldman Cool, thanks for your feedback anyway!
