### ISSUE TITLE
usability functions / wrapper?

### ISSUE THREAD

**Issue by bf** [ikr/money-math#23]
Hey ikr, I really like your library!

Is there already some sort of wrapper for it that adds some convenience functions like `.isNegative()` and some other shorthand functions (e.g. for `floatToAmount`) which allows for more readable code?

If no, would you want a bit more usability to be added to this project via pull request, or should I fork?

**Comment by ikr** [comment]
Hi there! Thank you.

Sure, I'd merge isNegative. With the other functions, could you please show exactly what you mean? A few examples would be great.

**Comment by ikr** [comment]
Just published v2.5.0
Thanks for your contribution!

**Comment by bf** [comment]
@ikr thanks for making a sane money calculation library for node.js!! Much appreciated!
