### ISSUE TITLE
Possibly wrong result after multiplication

### ISSUE THREAD

**Issue by magnusjt** [ikr/money-math#28]
Multiplying these two numbers together seems to yield the wrong result:

`let result = money.mul('2090.50', '8.61') // = 17999.20`

Should be 17999.21.

I guess this is because the bigint library doesn't round.. Is this intended?

**Comment by ikr** [comment]
Oh wow, thanks a lot Magnus for reporting that! It was a bug indeed. Now fixed in v2.5.1.
