### ISSUE TITLE
Add support for cryptocurrencies 

### ISSUE THREAD

**Issue by popenkomaksim** [ikr/money-math#29]
Hi.
First of all thanks for such a great project!

Do you have any particular vision of adding cryptocurrencies assets support?

Biggest challenge that smallest unit is differs from asset to asset, for example:
BTC: 0.00000001
ETH: 0.000000000000000001

Thanks,
Maksym

**Comment by ikr** [comment]
Hi Maksym

Thanks for your kind words.

Yeah, it must be a popular demand these days :) However, I'm afraid, that's out of the scope of this library. It's main thing always was only being a closed algebraic system with basic operations over _amounts,_ that _must_ look like `±XXX.XX`. I don't have an intention of growing it into a universal package covering the crypto-currencies as well.

**Comment by popenkomaksim** [comment]
Huge thanks for quick reply!
And kudos for clarifications
