### ISSUE TITLE
NaN calculates a multiplication

### ISSUE THREAD

**Issue by ralphkocher** [ikr/money-math#31]
The following multiplication results in a number result regardless one of the input factors is NaN:

a:  NaN
b:  18.00
const moneyTest = money.mul(a, b);

Result: moneyTest:  436.14

Shouldnt money-math handle the NaN?

**Comment by ikr** [comment]
money-math assumes that the arguments it operates on are valid _amounts._ I plan to port the library to TypeScript in order to help enforcing that.
