### ISSUE TITLE
Feature request : Function to convert zero decimal amount to readable currency

### ISSUE THREAD

**Issue by rohitm** [ikr/money-math#32]
Currency amounts are usually stored in databases without decimal points (i.e in cents). Can we have a function to convert the zero decimal number into readable currency. Roughly like below?

```
// TODO : Add unit tests
// Add tests to check if amount is an Integer
// Make sure amount isn't negative
// Make sure amount has some arbitrary upper limit. Don't want to be crunching ten billion -gazillion dollars

const amountToReadableCurrency = amount => (parseFloat(parseInt(amount, 10) / 100).toFixed(2));
```

**Comment by ikr** [comment]
There's `Money.amountToCents` which isn't documented in the README. Would it be good enough?

**Comment by rohitm** [comment]
@ikr I'm looking for the reverse - `Money.centsToAmount`

**Comment by rohitm** [comment]
And I just check the source and you have that function too. It would be helpful to document it.
