### ISSUE TITLE
Shouldn't money.div(a, b) ceil, instead of floor?

### ISSUE THREAD

**Issue by sliterok** [ikr/money-math#33]
```
var money = require("money-math");
money.div('1.00', '1000.00');
//0.00
```
It'd be great if you add ability to pass a third argument, specifyng whether function should floor or ceil.

**Comment by ikr** [comment]
At the moment, the division is simply a pass-through to the integer division on cents, covered by the BigNumber back-end. Yeah, I agree, introducing [various rounding modes](https://docs.oracle.com/en/java/javase/14/docs/api/java.base/java/math/RoundingMode.html) would be useful.

Currently though, as I'm not using the library myself anymore, there aren't any development plans. Of course, if someone implements the feature nicely, I'd merge it in. In general, I'd hand over the project to a new more invested maintainer.
