### ISSUE TITLE
Wrong result in floatToAmount

### ISSUE THREAD

**Issue by magnusjt** [ikr/money-math#34]
money.floatToAmount(8.165) // 8.16 (incorrect)
money.floatToAmount(8.175) // 8.18 (correct)

The reason it fails is because of the rounding logic in floatToAmount:
8.175 * 100.0 // = 817.5000000000001 -> Rounds to 818
8.165 * 100.0 // = 816.4999999999999 -> Rounds to 816

**Comment by ikr** [comment]
Yep, definitely a bug. Will fix, thanks!

**Comment by ikr** [comment]
Fixed in money-math@2.6.1
