### ISSUE TITLE
amountToCents works poorly

### ISSUE THREAD

**Issue by mattdawson** [ikr/money-math#4]
amountToCents("10") returns 10, should return 1000
amountToCents("10.1") returns 101, should return 1010
amountToCents("10.111") returns 10111, should error
amountToCents(10) should either return 1000, or error on 10 not being a string.

**Comment by ikr** [comment]
Hi Matt

As stated in the README, money-math operates on _amounts_ – the strings, strictly matching the `/^\-?\d+\.\d\d$/` pattern, like "0.25", "1000.00", or "-42.10". None of the values in your examples is an _amount._

**Comment by ikr** [comment]
Please use `money.floatToAmount()` to cast stuff into the amount "data type".

**Comment by ikr** [comment]
@mattdawson It's not the 1st time I'm getting asked that. Decided to clarify the issue [in the README](https://github.com/ikr/money-math#an-important-note-on-the-amount-data-type)
