### ISSUE TITLE
More currency formats

### ISSUE THREAD

**Issue by larsnystrom** [ikr/money-math#9]
Would you consider adding the format `# ###,##`? 

This is how e.g. SEK (Swedish krona) is usually formatted. According to [this page](http://www.thefinancials.com/?SubSectionID=curformat) Lithuanian Litas (LTL), Polish Zloty (PLN), Slovak Koruna (SKK) and Ukraine Hryvnia (UAH) also uses this format.

I'd also like to thank you for this package. I like the clean interface!

**Comment by ikr** [comment]
Sure, PR's welcome! :hand:

**Comment by larsnystrom** [comment]
Great, I'll get to it then.

**Comment by larsnystrom** [comment]
Included in v2.4.0. Thank you!
